<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>task_005_interbotix_demo</name>
  <version>0.0.1</version>
  <description>ROS2 migration of Interbotix XSArm perception pick and place demo</description>
  <maintainer email="dev@example.com">dev</maintainer>
  <license>BSD</license>

  <exec_depend>rclpy</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>